# Generated by Django 4.2.10 on 2024-04-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='type',
            field=models.CharField(default='scifi', max_length=100),
        ),
    ]
