# Generated by Django 4.2.10 on 2024-04-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='type',
            new_name='typ',
        ),
    ]
